---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: php-demo
    spec:
      containers:
      - name: php-demo
        image: harbor.corp.local/public/php-demo:${MY_BUILD_IDENTIFIER}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-demo
  labels:
    app: php-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: php-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: demo.corp.local
    http:
      paths:
      - path: /
        backend:
          serviceName: php-demo
          servicePort: 80
