---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php-demo
    spec:
      containers:
      - name: php-demo
        image: harbor.corp.local/public/php-demo:${MY_BUILD_IDENTIFIER}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-demo
  labels:
    app: php-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: php-demo